version: '3'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    depends_on:
      - db
    environment:
      - DJANGO_SETTINGS_MODULE=community_events.settings
    networks:
      - backend

  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=community_events_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
    networks:
      - backend

networks:
  backend:
    driver: bridge
